# Generated by Django 3.2.10 on 2022-01-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=40)),
                ('description', models.CharField(default='', max_length=200)),
                ('birth_date', models.DateField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
