# Generated by Django 3.2.10 on 2022-01-30 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completionDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
